name: proxity_flutter
description: Proxity flutter plugin for iOS and Android
version: 0.0.3
homepage: https://github.com/proxity-eu/proxity_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.proxity.proxity_flutter
        pluginClass: ProxityFlutterPlugin
      ios:
        pluginClass: ProxityFlutterPlugin
